package json

data class Beatmap(
    val approved: Byte, //future enum implementation
    val submit_date: String,
    val approved_date: String,
    val last_update: String,
    val artist: String,
    val beatmap_id: Long,
    val beatmapset_id: Long,
    val bpm: Double,
    val creator: String,
    val creator_id: Long,
    val difficultyrating: Double,
    val diff_aim: Double,
    val diff_speed: Double,
    val diff_size: Float,
    val diff_overall: Float,
    val diff_approach: Float,
    val diff_drain: Float,
    val hit_length: Int,
    val source: String,
    val genre_id: Byte,
    val language_id: Byte,
    val title: String,
    val total_length: Int,
    val version: String,
    val file_md5: String,
    val mode: Byte,
    val tags: String,
    val favourite_count: Int,
    val rating: Double,
    val playcount: Int,
    val passcount: Int,
    val count_normal: Int,
    val count_slider: Int,
    val count_spinner: Int,
    val max_combo: Int,
    val download_unavailable: Byte,
    val audio_unavailable: Byte
)
